#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Veyon documentation build configuration file, created by
# sphinx-quickstart on Tue May  2 08:20:52 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
sys.path.insert(0, os.path.abspath('.'))


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.coverage',
    'sphinx.ext.ifconfig',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'SIINEOS'
copyright = '2025, in.hub GmbH'
author = 'in.hub GmbH'

title = os.getenv('TITLE', 'SIINEOS Documentation')
# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '2.9.5'
# The full version, including alpha/beta/rc tags.
release = version

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = os.getenv('LANGUAGE', None)

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

html_context = {
    'display_github': False
}

html_theme_options = {
    'canonical_url': 'https://siineos.readthedocs.io',
    'display_version': False,
    'prev_next_buttons_location': None,
    'sticky_navigation': False
}


# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_css_files = [
    'theme_overrides.css',
]

# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'siineosdoc'


# -- Options for LaTeX output ---------------------------------------------
latex_engine = 'xelatex'

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    'papersize': os.getenv('PAPER', 'a4paper'),

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    'preamble': r'''
\usepackage{titlesec}
\usepackage{color}
\titleformat{\chapter}[display]{\normalfont\Large\bfseries}{\chaptertitlename\ \thechapter}{10pt}{\huge}
\titlespacing*{\chapter}{0pt}{0pt}{10pt}
\usepackage[protrusion=true,babel=true,shrink=10,stretch=10]{microtype}
\fancypagestyle{normal}{
       \fancyhf{}
       \fancyfoot[C]{{\thepage}}
       \fancyhead[L]{{\nouppercase\Title{}}}
       \fancyhead[R]{{\nouppercase\rightmark}}
}
\definecolor{guilabel}{HTML}{b5e6de}
\definecolor{guilabelframe}{HTML}{5dc8b6}
''',
	'tableofcontents': r'''\sphinxtableofcontents
\makeatletter\let\Title\@title\makeatother
\pagestyle{normal}
\renewcommand{\sphinxmenuselection}[1]{\fcolorbox{guilabelframe}{guilabel}{#1}}
''',
    'babel': '\\usepackage[%s]{babel}' % (os.getenv('BABEL', 'USenglish')),
    'fontpkg': r'''
\setmainfont[ItalicFont={Dosis-Bold}]{Dosis}
\setsansfont[ItalicFont={Dosis-Bold}]{Dosis}
''',
    'figure_align': 'H',
    'printindex': '',

}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    ('index', 'siineos-manual.tex', 'SIINEOS Manual', author, 'howto'),
]

html_logo = 'logo.svg'
latex_logo = 'logo.pdf'

locale_dirs = [ 'locale/' ]
gettext_compact = True
gettext_location = False
gettext_additional_targets = ['index']
figure_language_filename = '{path}{language}/{basename}{ext}'

qthelp_namespace = 'de.inhub.SIINEOS.%s' % ( version )

numfig = True
